#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/library_dev
#    username: dev_user
#    password: dev_password
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

#spring.application.name=library-service
server:
  port: 8081

spring:
  application:
    name: library-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: warn