services:

  db:
    image: postgres:16
    container_name: library-postgres
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - library_system_data:/var/lib/postgresql/data
    networks:
      - infra_network

  library-service:
    image: ghcr.io/darkenergymv/library-app:latest
    container_name: library-app
    depends_on:
      - db
    env_file:
      - ../.env
    ports:
      - "8081:8081"
    networks:
      - infra_network

networks:
  infra_network:
    name: library_system_infra_network
    driver: bridge

volumes:
  library_system_data:
